version: '3'
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    expose:
      - "5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - "./backend:/backend"
    ports:
      - "127.0.0.1:${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    links:
      - db
    tty: true
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_PORT: ${APP_PORT}
