version: '3'
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    expose:
      - "5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - "./backend:/backend"
    ports:
      - "8080"
    expose:
      - "8080"
    depends_on:
      - db
    tty: true
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
